config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  resources :categories, only: [:show]
  resources :services, only: [:show, :create, :index, :edit, :destroy] do
    resources :reviews, only: [:create, :index]
  end
  resources :messages, only: [:index, :create, :destroy]
  resources :reviews, only: [:destroy]
  resources :users, only: [:new, :create]
  resources :searchbar, only: [:index]
  post '/services/new' => 'services#new'
end

app/views/layouts/_top_nav.html.erb
<nav>
  <div class="nav-wrapper blue darken-2 ">
    <%= image_tag 'logo.svg',size: "62x62", class: "img-responsive2" %>
    <a href="/" class="brand-logo"><i><b><h4>BluCollar</h4></b></i></a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Messages", messages_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "My Service", service_path(:id => current_user.id) %></li>
        <li>Welcome <%= current_user.email %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: 'DELETE' %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
      <% end %>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "Messages", messages_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "My Service", service_path(:id => current_user.id) %></li>
        <li>Welcome <%= current_user.email %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: 'DELETE' %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Register", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js'%>

  </head>
  <body>
    <%= render 'layouts/top_nav' %>

    <div class="right">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    
    <%= yield %>
  </body>
</html>